### PR TITLE
Allow renaming the serverHost globally and all sessionInfo per-log-group

### PR DESCRIPTION
**Pull request by redterror**
This adds support for 2 new env vars:

`SERVER_HOST` - String: sets the server host as a global default
`LOG_GROUP_OPTIONS` - JSON: allows overriding `sessionInfo` on a per-log-group basis.

My use case here was to support renaming ugly / confusing log names (e.g. `API-Gateway-Execution-Logs_abcdef123456`) to something sane.

### CODE REVIEW

**Review by soboko — APPROVED** [review]
I'd add semicolons on the lines you added in transformToAddEventsMessage (just for stylistic consistency with the rest of the code). Otherwise, LGTM 👍

**Comment by redterror** [comment]
Pushed those.  :)  I've been in ES6 land lately!

**Comment by redterror** [comment]
@soboko does this look like its ready to merge or does it need more?

**Comment by soboko** [comment]
LGTM :)

**Pull request merged**
